/* Generated by Yosys 0.15+38 (git sha1 66914b6eb, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module blink3(\blink^clk , \blink^i_reset , \blink^read_mtj , \blink^write_mtj , \blink^o_led );
  wire \0 ;
  wire \blink^ADD~2-0[0] ;
  wire \blink^ADD~2-0~dummy_output~0~1 ;
  wire \blink^ADD~2-1[0] ;
  wire \blink^ADD~2-1[1] ;
  wire \blink^ADD~2-2[0] ;
  wire \blink^ADD~2-2[1] ;
  wire \blink^ADD~2-3[0] ;
  wire \blink^ADD~2-3[1] ;
  wire \blink^ADD~2-4[0] ;
  wire \blink^ADD~2-4[1] ;
  wire \blink^ADD~2-5[0] ;
  wire \blink^ADD~2-5[1] ;
  input \blink^clk ;
  wire \blink^clk ;
  input \blink^i_reset ;
  wire \blink^i_reset ;
  wire \blink^nMUX~0^MUX_2~25 ;
  wire \blink^nMUX~0^MUX_2~26 ;
  wire \blink^nMUX~0^MUX_2~27 ;
  output \blink^o_led ;
  wire \blink^o_led ;
  reg \blink^r_counter~0_FF  = 1'h0;
  reg \blink^r_counter~1_FF  = 1'h0;
  wire \blink^r_counter~2_FF ;
  wire \blink^r_counter~3_FF ;
  wire \blink^r_counter~4_FF ;
  input \blink^read_mtj ;
  wire \blink^read_mtj ;
  input \blink^write_mtj ;
  wire \blink^write_mtj ;
  wire gnd;
  wire n19;
  wire n24;
  wire n29;
  wire n34;
  wire n39;
  wire unconn;
  wire vcc;
  always @(posedge \blink^clk )
    \blink^r_counter~1_FF  <= n39;
  always @(posedge \blink^clk )
    \blink^r_counter~0_FF  <= n19;
  adder _02_ (
    .\a (\blink^r_counter~0_FF ),
    .\b (vcc),
    .\cin (\blink^ADD~2-0[0] ),
    .\cout (\blink^ADD~2-1[0] ),
    .\sumout (\blink^ADD~2-1[1] )
  );
  nonvolatile_ff _03_ (
    .\clk (\blink^clk ),
    .\d (\blink^nMUX~0^MUX_2~25 ),
    .\q (\blink^r_counter~2_FF ),
    .\read_mtj (\blink^read_mtj),
    .\rst (\blink^i_reset ),
    .\write_mtj (\blink^write_mtj )
  );
  adder _04_ (
    .\a (\blink^r_counter~1_FF ),
    .\b (gnd),
    .\cin (\blink^ADD~2-1[0] ),
    .\cout (\blink^ADD~2-2[0] ),
    .\sumout (\blink^ADD~2-2[1] )
  );
  adder _05_ (
    .\a (\blink^r_counter~2_FF ),
    .\b (gnd),
    .\cin (\blink^ADD~2-2[0] ),
    .\cout (\blink^ADD~2-3[0] ),
    .\sumout (\blink^ADD~2-3[1] )
  );
  adder _06_ (
    .\a (\blink^r_counter~3_FF ),
    .\b (gnd),
    .\cin (\blink^ADD~2-3[0] ),
    .\cout (\blink^ADD~2-4[0] ),
    .\sumout (\blink^ADD~2-4[1] )
  );
  adder _07_ (
    .\a (\blink^r_counter~4_FF ),
    .\b (gnd),
    .\cin (\blink^ADD~2-4[0] ),
    .\cout (\blink^ADD~2-5[0] ),
    .\sumout (\blink^ADD~2-5[1] )
  );
  adder _08_ (
    .\a (vcc),
    .\b (gnd),
    .\cin (unconn),
    .\cout (\blink^ADD~2-0[0] ),
    .\sumout (\blink^ADD~2-0~dummy_output~0~1 )
  );
  nonvolatile_ff _09_ (
    .\clk (\blink^clk ),
    .\d (\blink^nMUX~0^MUX_2~27 ),
    .\q (\blink^r_counter~4_FF ),
    .\read_mtj (\blink^read_mtj ),
    .\rst (\blink^i_reset ),
    .\write_mtj (\0 )
  );
  nonvolatile_ff _10_ (
    .\clk (\blink^clk ),
    .\d (\blink^nMUX~0^MUX_2~26 ),
    .\q (\blink^r_counter~3_FF ),
    .\read_mtj (\blink^read_mtj ),
    .\rst (\blink^i_reset ),
    .\write_mtj (\0 )
  );
  assign n19 = 4'h4 >> { \blink^ADD~2-1[1] , \blink^i_reset  };
  assign n24 = 4'h4 >> { \blink^ADD~2-5[1] , \blink^i_reset  };
  assign n29 = 4'h4 >> { \blink^ADD~2-4[1] , \blink^i_reset  };
  assign n34 = 4'h4 >> { \blink^ADD~2-3[1] , \blink^i_reset  };
  assign n39 = 4'h4 >> { \blink^ADD~2-2[1] , \blink^i_reset  };
  assign \blink^o_led  = 2'h1 >> \blink^r_counter~4_FF ;
  assign vcc = 1'h1;
  assign gnd = 1'h0;
  assign unconn = 1'h0;
endmodule
